services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: development_pass
      POSTGRES_MULTIPLE_DATABASES: "api-database,api-testing-database"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - api_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  api_data:
